[Auth]
apikey = ''                                 # Your steam API-key (https://steamcommunity.com/dev/apikey)

[SQL]
hostname = 'localhost'                      # MySQL server hostname
port = '3306'                               # MySQL server port
username =  ''                              # MySQL username
password = ''                               # MySQL password
db_name = ''                                # MySQL Database with 'grant all' rights

[Other]
steam_id = ''                               # Your steamID64 (https://steamid.io/lookup)
currency = 'EUR'                            # Currency code (https://en.wikipedia.org/wiki/ISO_4217#Active_codes)
idfile = false                              # If this is set to true create/use a file containing steam ids to scan
